apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_DATABASE_TYPE
              value: "postgres"
            - name: GF_DATABASE_HOST
              value: "grafana-postgres:5432"     # ou l'adresse IP du service PostgreSQL
            - name: GF_DATABASE_NAME
              value: "grafana"
            - name: GF_DATABASE_USER
              value: "grafana"
            - name: GF_DATABASE_PASSWORD
              value: "grafana_pass"
            - name: GF_DATABASE_SSL_MODE
              value: "disable"


